# This workflow will build a package using Maven and then publish it to GitHub packages
# Triggered manually from the GitHub UI

name: Maven Package

on:
  workflow_dispatch: # This enables the manual trigger

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 16
      uses: actions/setup-java@v4
      with:
        java-version: '16'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
